version: '3.8'
services:
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=defaultdb
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5434:5432'
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data

  users:
    build:
      context: ./users-microservice
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/defaultdb
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres
