version: '3.8'
services:
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=defaultdb
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5434:5432'
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql164/data

volumes:
  postgres:
    driver: local
